### ISSUE TITLE
tar: This does not look like a tar archive

### ISSUE THREAD

**Issue by ibardarov-fms** [looztra/asdf-k9s#30] opened 2023-07-11 16:49 UTC
Hi,
I tried to install the latest version and I got an erro

```
❯ asdf plugin-add k9s https://github.com/looztra/asdf-k9s

∴ asdf install k9s latst
/home/uda/.asdf/plugins/k9s/bin/install: line 74: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 77: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 74: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 77: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 74: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 77: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 74: ((: 10#latst: value too great for base (error token is "10#latst")
/home/uda/.asdf/plugins/k9s/bin/install: line 77: ((: 10#latst: value too great for base (error token is "10#latst")
[2023-07-11 19:46:25] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/latst/k9s_latst_Linux_x86_64.tar.gz to /tmp/asdf_cZGbvFTT/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
[2023-07-11 19:46:26] INFO: Creating bin directory [/home/uda/.asdf/installs/k9s/latst/bin] (install_tool)
[2023-07-11 19:46:26] INFO: Cleaning previous binaries if any (install_tool)
[2023-07-11 19:46:26] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


```

**Comment by moss2k13** [comment] 2024-01-09 11:20
i can confirm with any other k9s versions higher than 0.26.3:
```
 2024-01-09 12:13:54 ⌚  PF-3ASX5A in ~
○ → asdf install k9s latest
[2024-01-09 12:15:31] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.31.1/k9s_Linux_x86_64.tar.gz to /tmp/asdf_BJGwlsBY/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
[2024-01-09 12:15:31] INFO: Creating bin directory [/home/mossapio/.asdf/installs/k9s/0.31.1/bin] (install_tool)
[2024-01-09 12:15:31] INFO: Cleaning previous binaries if any (install_tool)
[2024-01-09 12:15:31] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


 2024-01-09 12:12:52 ⌚  PF-3ASX5A in ~
○ → asdf install k9s 0.30.8
[2024-01-09 12:13:04] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.30.8/k9s_Linux_x86_64.tar.gz to /tmp/asdf_oWoDlMW0/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
[2024-01-09 12:13:05] INFO: Creating bin directory [/home/mossapio/.asdf/installs/k9s/0.30.8/bin] (install_tool)
[2024-01-09 12:13:05] INFO: Cleaning previous binaries if any (install_tool)
[2024-01-09 12:13:05] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


 2024-01-09 12:13:05 ⌚  PF-3ASX5A in ~
○ → asdf install k9s 0.29.1
[2024-01-09 12:13:18] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.29.1/k9s_Linux_x86_64.tar.gz to /tmp/asdf_OMXOC8Db/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     18      0 --:--:-- --:--:-- --:--:--    19
[2024-01-09 12:13:18] INFO: Creating bin directory [/home/mossapio/.asdf/installs/k9s/0.29.1/bin] (install_tool)
[2024-01-09 12:13:18] INFO: Cleaning previous binaries if any (install_tool)
[2024-01-09 12:13:18] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


 2024-01-09 12:13:18 ⌚  PF-3ASX5A in ~
○ → asdf install k9s 0.28.2
[2024-01-09 12:13:29] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.28.2/k9s_Linux_x86_64.tar.gz to /tmp/asdf_USVS56y9/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     24      0 --:--:-- --:--:-- --:--:--    24
[2024-01-09 12:13:29] INFO: Creating bin directory [/home/mossapio/.asdf/installs/k9s/0.28.2/bin] (install_tool)
[2024-01-09 12:13:29] INFO: Cleaning previous binaries if any (install_tool)
[2024-01-09 12:13:29] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


 2024-01-09 12:13:46 ⌚  PF-3ASX5A in ~
○ → asdf install k9s 0.27.4
[2024-01-09 12:13:48] INFO: Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_x86_64.tar.gz to /tmp/asdf_Q07zOS7I/sub/k9s_Linux_x86_64.tar.gz (install_tool)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0      1      0  0:00:09  0:00:05  0:00:04     2
[2024-01-09 12:13:54] INFO: Creating bin directory [/home/mossapio/.asdf/installs/k9s/0.27.4/bin] (install_tool)
[2024-01-09 12:13:54] INFO: Cleaning previous binaries if any (install_tool)
[2024-01-09 12:13:54] INFO: Extracting archive (install_tool)
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


 2024-01-09 12:15:31 ⌚  PF-3ASX5A in ~
○ → asdf list k9s 
 *0.26.3
```
@ibardarov-fms  you have a typo:
`∴ asdf install k9s latst`
but for `latest` it still doesn't work

**Comment by moss2k13** [comment] 2024-01-09 12:03
workaround:
```
asdf plugin-add k9s https://github.com/virtualstaticvoid/asdf-k9s.git
asdf install k9s latest
asdf list k9s
 *0.31.1
```

**Comment by looztra** [comment] 2024-08-23 14:14
@moss2k13 so nice of you to provide a fork instead of crafting a PR 😢

**Comment by looztra** [comment] 2024-08-23 14:17
@ibardarov-fms @moss2k13 which platform are you trying to install k9s on?

This works for me on `Darwin_arm64`

**Comment by looztra** [comment] 2024-08-23 15:43
I've updated the CI to check more stuff on both macos (Darwin) and linux.
Everything is fine.

Closing the issue.

Feel free to reopen with more information/context if you still have troubles

**Closed by looztra** 2024-08-23 15:43 UTC
